// examples/simple-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { IfcViewerAPI } from 'web-ifc-viewer';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'ifcjs-angular-example';
  viewer?: IfcViewerAPI;

  ngOnInit(){
    
    const container = document.getElementById("viewer-container")!;
    this.viewer = new IfcViewerAPI({container});
    console.log(this.viewer);
    this.viewer.addAxes();
    this.viewer.addGrid();
    this.viewer.setWasmPath("assets/");

    const url = "https://raw.githubusercontent.com/IFCjs/test-ifc-files/main/Revit/TESTED_Simple_project_01.ifc";
    this.viewer.loadIfcUrl(url);
    
    //Setup loader
    // const loadIfc = async (event) => {
    //    await viewer.loadIfc(event.target.files[0], true);
    // }
    
    // const inputElement = document.createElement('input');
    // inputElement.setAttribute('type', 'file');
    // inputElement.classList.add('hidden');
    // inputElement.addEventListener('change', loadIfc, false);
    // document.body.appendChild(inputElement);
    
    // const handleKeyDown = (event) => {
    //     viewer.removeClippingPlane();
    // };
    
    // window.onmousemove = viewer.preselectIfcItem;
    // window.onkeydown = handleKeyDown;
    // window.ondblclick = viewer.addClippingPlane;
    
    //Setup UI
    // const loadButton = createSideMenuButton('./resources/folder-icon.svg');
    //     loadButton.addEventListener('click', () => {
    //     loadButton.blur();
    //     inputElement.click();
    // });
    
    // const sectionButton = createSideMenuButton('./resources/section-plane-down.svg');
    // sectionButton.addEventListener('click', () => {
    //     sectionButton.blur();
    //     viewer.toggleClippingPlanes();
    // });
    
    // const dropBoxButton = createSideMenuButton('./resources/dropbox-icon.svg');
    // dropBoxButton.addEventListener('click', () => {
    //     dropBoxButton.blur();
    //     viewer.openDropboxWindow();
    // });
  }
}

<aside class="side-menu" id="side-menu-left"></aside>
<div id="viewer-container" style="width: 100vw; height: 100vh"></div>

// examples/simple-svelte/src/App.svelte
<script>
	import { onMount } from 'svelte';
	import { IfcViewerAPI } from 'web-ifc-viewer';

	let viewer, fileInput
	onMount(async() => {
		const container = document.getElementById("viewer-container");
	viewer = new IfcViewerAPI({container});
	viewer.addAxes();
	viewer.addGrid();
	viewer.setWasmPath("wasm/");
	})
	

	//Setup loader
	const loadIfc = async (event) => {
   		await viewer.loadIfc(event.target.files[0], true);
	}

</script>

<main>
	<aside class="side-menu" id="side-menu-left">
		<input style="display:none" type="file" accept=".ifc" on:change={(e)=>loadIfc(e)} bind:this={fileInput}>
		<button on:click={()=>fileInput.click()}><img src='static/folder-icon.svg' alt='load file' class='icon'></button>
		{#if viewer}
		<button on:click={viewer.toggleClippingPlanes()}><img src='static/section-plane-down.svg' alt='clipping panes' class='icon'></button>
		<button on:click={viewer.openDropboxWindow()}><img src='static/dropbox-icon.svg' alt='dropbox' class='icon'></button>
		{/if}
	</aside>
	<div id="viewer-container" 
		style="width: 100vw; height: 100vh" 
		on:mousemove={viewer.prepickIfcItem} 
		on:keydown={viewer.removeClippingPlane()}
		on:dblclick={viewer.addClippingPlane}>
	</div>
</main>

<style>
	.side-menu {
    	z-index: 1;
    	position: fixed;
    	background-color: #36393F;
    	height:100vh;
	}

	#side-menu-left {
	    width: 40px;
	}
</style>
